# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92b041cb1f71701b746d1144b290b0ae85f4f2e28795aad7f531964ae5fb5f37a6f5b5ee47c0d4ac409de9bf4e40ff8765173f8547958bbf64165c9a163c8790

test:
  secret_key_base: ea9e68ac4572d03b2f17160c0b9d35100e5d933f1282302f325d8e54b41f83fc30196e81bf20548141a2be64dea113c48f18d9e2be437edc115b45dee4c2ea3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
